LINHAS = 15
COLUNAS = 15
TAMANHO_BLOCO = 48
PAINEL_LATERAL = 300
LARGURA_TELA = TAMANHO_BLOCO * COLUNAS
ALTURA_TELA = TAMANHO_BLOCO * LINHAS
FPS = 60
SAUDE = 100
DINHEIRO = 200
TOTAL_NIVEIS = 4

#enemy constants
ESPERA_SURGIMENTO = 400

#turret constants
NIVEL_ARQUEIRO = 4
CUSTO = 200
CUSTO_UPGRADE = 100
RECOMPENSA = 1
RECOMPENSA_NIVEL = 200
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DANO = 5